// source: tensorflow/core/framework/model.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.tensorflow.data.model.AutotuneAlgorithm', null, global);
goog.exportSymbol('proto.tensorflow.data.model.ModelProto', null, global);
goog.exportSymbol('proto.tensorflow.data.model.ModelProto.Node', null, global);
goog.exportSymbol('proto.tensorflow.data.model.ModelProto.Node.Parameter', null, global);
goog.exportSymbol('proto.tensorflow.data.model.ModelProto.OptimizationParams', null, global);
goog.exportSymbol('proto.tensorflow.data.model.NodeClass', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tensorflow.data.model.ModelProto = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.tensorflow.data.model.ModelProto, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.tensorflow.data.model.ModelProto.displayName = 'proto.tensorflow.data.model.ModelProto';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tensorflow.data.model.ModelProto.Node = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.tensorflow.data.model.ModelProto.Node.repeatedFields_, null);
};
goog.inherits(proto.tensorflow.data.model.ModelProto.Node, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.tensorflow.data.model.ModelProto.Node.displayName = 'proto.tensorflow.data.model.ModelProto.Node';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tensorflow.data.model.ModelProto.Node.Parameter = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.tensorflow.data.model.ModelProto.Node.Parameter, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.tensorflow.data.model.ModelProto.Node.Parameter.displayName = 'proto.tensorflow.data.model.ModelProto.Node.Parameter';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tensorflow.data.model.ModelProto.OptimizationParams = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.tensorflow.data.model.ModelProto.OptimizationParams, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.tensorflow.data.model.ModelProto.OptimizationParams.displayName = 'proto.tensorflow.data.model.ModelProto.OptimizationParams';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tensorflow.data.model.ModelProto.prototype.toObject = function(opt_includeInstance) {
  return proto.tensorflow.data.model.ModelProto.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tensorflow.data.model.ModelProto} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tensorflow.data.model.ModelProto.toObject = function(includeInstance, msg) {
  var f, obj = {
    output: (f = msg.getOutput()) && proto.tensorflow.data.model.ModelProto.Node.toObject(includeInstance, f),
    idCounter: jspb.Message.getFieldWithDefault(msg, 2, 0),
    collectResourceUsage: jspb.Message.getBooleanFieldWithDefault(msg, 3, false),
    optimizationParams: (f = msg.getOptimizationParams()) && proto.tensorflow.data.model.ModelProto.OptimizationParams.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tensorflow.data.model.ModelProto}
 */
proto.tensorflow.data.model.ModelProto.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tensorflow.data.model.ModelProto;
  return proto.tensorflow.data.model.ModelProto.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tensorflow.data.model.ModelProto} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tensorflow.data.model.ModelProto}
 */
proto.tensorflow.data.model.ModelProto.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.tensorflow.data.model.ModelProto.Node;
      reader.readMessage(value,proto.tensorflow.data.model.ModelProto.Node.deserializeBinaryFromReader);
      msg.setOutput(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setIdCounter(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setCollectResourceUsage(value);
      break;
    case 4:
      var value = new proto.tensorflow.data.model.ModelProto.OptimizationParams;
      reader.readMessage(value,proto.tensorflow.data.model.ModelProto.OptimizationParams.deserializeBinaryFromReader);
      msg.setOptimizationParams(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tensorflow.data.model.ModelProto.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tensorflow.data.model.ModelProto.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tensorflow.data.model.ModelProto} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tensorflow.data.model.ModelProto.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOutput();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.tensorflow.data.model.ModelProto.Node.serializeBinaryToWriter
    );
  }
  f = message.getIdCounter();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getCollectResourceUsage();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getOptimizationParams();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.tensorflow.data.model.ModelProto.OptimizationParams.serializeBinaryToWriter
    );
  }
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.tensorflow.data.model.ModelProto.Node.repeatedFields_ = [11,14];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tensorflow.data.model.ModelProto.Node.prototype.toObject = function(opt_includeInstance) {
  return proto.tensorflow.data.model.ModelProto.Node.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tensorflow.data.model.ModelProto.Node} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tensorflow.data.model.ModelProto.Node.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    name: jspb.Message.getFieldWithDefault(msg, 2, ""),
    autotune: jspb.Message.getBooleanFieldWithDefault(msg, 3, false),
    bufferedBytes: jspb.Message.getFieldWithDefault(msg, 4, 0),
    bufferedElements: jspb.Message.getFieldWithDefault(msg, 5, 0),
    bytesConsumed: jspb.Message.getFieldWithDefault(msg, 6, 0),
    bytesProduced: jspb.Message.getFieldWithDefault(msg, 7, 0),
    numElements: jspb.Message.getFieldWithDefault(msg, 8, 0),
    processingTime: jspb.Message.getFieldWithDefault(msg, 9, 0),
    recordMetrics: jspb.Message.getBooleanFieldWithDefault(msg, 10, false),
    parametersList: jspb.Message.toObjectList(msg.getParametersList(),
    proto.tensorflow.data.model.ModelProto.Node.Parameter.toObject, includeInstance),
    inputProcessingTimeSum: jspb.Message.getFloatingPointFieldWithDefault(msg, 12, 0.0),
    inputProcessingTimeCount: jspb.Message.getFieldWithDefault(msg, 13, 0),
    inputsList: jspb.Message.toObjectList(msg.getInputsList(),
    proto.tensorflow.data.model.ModelProto.Node.toObject, includeInstance),
    nodeClass: jspb.Message.getFieldWithDefault(msg, 15, 0),
    ratio: jspb.Message.getFloatingPointFieldWithDefault(msg, 16, 0.0),
    memoryRatio: jspb.Message.getFloatingPointFieldWithDefault(msg, 17, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tensorflow.data.model.ModelProto.Node}
 */
proto.tensorflow.data.model.ModelProto.Node.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tensorflow.data.model.ModelProto.Node;
  return proto.tensorflow.data.model.ModelProto.Node.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tensorflow.data.model.ModelProto.Node} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tensorflow.data.model.ModelProto.Node}
 */
proto.tensorflow.data.model.ModelProto.Node.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAutotune(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setBufferedBytes(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setBufferedElements(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setBytesConsumed(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setBytesProduced(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setNumElements(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setProcessingTime(value);
      break;
    case 10:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setRecordMetrics(value);
      break;
    case 11:
      var value = new proto.tensorflow.data.model.ModelProto.Node.Parameter;
      reader.readMessage(value,proto.tensorflow.data.model.ModelProto.Node.Parameter.deserializeBinaryFromReader);
      msg.addParameters(value);
      break;
    case 12:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setInputProcessingTimeSum(value);
      break;
    case 13:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setInputProcessingTimeCount(value);
      break;
    case 14:
      var value = new proto.tensorflow.data.model.ModelProto.Node;
      reader.readMessage(value,proto.tensorflow.data.model.ModelProto.Node.deserializeBinaryFromReader);
      msg.addInputs(value);
      break;
    case 15:
      var value = /** @type {!proto.tensorflow.data.model.NodeClass} */ (reader.readEnum());
      msg.setNodeClass(value);
      break;
    case 16:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setRatio(value);
      break;
    case 17:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setMemoryRatio(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tensorflow.data.model.ModelProto.Node.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tensorflow.data.model.ModelProto.Node.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tensorflow.data.model.ModelProto.Node} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tensorflow.data.model.ModelProto.Node.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getAutotune();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getBufferedBytes();
  if (f !== 0) {
    writer.writeInt64(
      4,
      f
    );
  }
  f = message.getBufferedElements();
  if (f !== 0) {
    writer.writeInt64(
      5,
      f
    );
  }
  f = message.getBytesConsumed();
  if (f !== 0) {
    writer.writeInt64(
      6,
      f
    );
  }
  f = message.getBytesProduced();
  if (f !== 0) {
    writer.writeInt64(
      7,
      f
    );
  }
  f = message.getNumElements();
  if (f !== 0) {
    writer.writeInt64(
      8,
      f
    );
  }
  f = message.getProcessingTime();
  if (f !== 0) {
    writer.writeInt64(
      9,
      f
    );
  }
  f = message.getRecordMetrics();
  if (f) {
    writer.writeBool(
      10,
      f
    );
  }
  f = message.getParametersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      11,
      f,
      proto.tensorflow.data.model.ModelProto.Node.Parameter.serializeBinaryToWriter
    );
  }
  f = message.getInputProcessingTimeSum();
  if (f !== 0.0) {
    writer.writeDouble(
      12,
      f
    );
  }
  f = message.getInputProcessingTimeCount();
  if (f !== 0) {
    writer.writeInt64(
      13,
      f
    );
  }
  f = message.getInputsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      14,
      f,
      proto.tensorflow.data.model.ModelProto.Node.serializeBinaryToWriter
    );
  }
  f = message.getNodeClass();
  if (f !== 0.0) {
    writer.writeEnum(
      15,
      f
    );
  }
  f = message.getRatio();
  if (f !== 0.0) {
    writer.writeDouble(
      16,
      f
    );
  }
  f = message.getMemoryRatio();
  if (f !== 0.0) {
    writer.writeDouble(
      17,
      f
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tensorflow.data.model.ModelProto.Node.Parameter.prototype.toObject = function(opt_includeInstance) {
  return proto.tensorflow.data.model.ModelProto.Node.Parameter.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tensorflow.data.model.ModelProto.Node.Parameter} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tensorflow.data.model.ModelProto.Node.Parameter.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    value: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
    stateValue: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0),
    min: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0),
    max: jspb.Message.getFloatingPointFieldWithDefault(msg, 5, 0.0),
    tunable: jspb.Message.getBooleanFieldWithDefault(msg, 6, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tensorflow.data.model.ModelProto.Node.Parameter}
 */
proto.tensorflow.data.model.ModelProto.Node.Parameter.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tensorflow.data.model.ModelProto.Node.Parameter;
  return proto.tensorflow.data.model.ModelProto.Node.Parameter.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tensorflow.data.model.ModelProto.Node.Parameter} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tensorflow.data.model.ModelProto.Node.Parameter}
 */
proto.tensorflow.data.model.ModelProto.Node.Parameter.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setValue(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setStateValue(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setMin(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setMax(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setTunable(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tensorflow.data.model.ModelProto.Node.Parameter.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tensorflow.data.model.ModelProto.Node.Parameter.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tensorflow.data.model.ModelProto.Node.Parameter} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tensorflow.data.model.ModelProto.Node.Parameter.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getValue();
  if (f !== 0.0) {
    writer.writeDouble(
      2,
      f
    );
  }
  f = message.getStateValue();
  if (f !== 0.0) {
    writer.writeDouble(
      3,
      f
    );
  }
  f = message.getMin();
  if (f !== 0.0) {
    writer.writeDouble(
      4,
      f
    );
  }
  f = message.getMax();
  if (f !== 0.0) {
    writer.writeDouble(
      5,
      f
    );
  }
  f = message.getTunable();
  if (f) {
    writer.writeBool(
      6,
      f
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.tensorflow.data.model.ModelProto.Node.Parameter.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.tensorflow.data.model.ModelProto.Node.Parameter} returns this
 */
proto.tensorflow.data.model.ModelProto.Node.Parameter.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional double value = 2;
 * @return {number}
 */
proto.tensorflow.data.model.ModelProto.Node.Parameter.prototype.getValue = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.tensorflow.data.model.ModelProto.Node.Parameter} returns this
 */
proto.tensorflow.data.model.ModelProto.Node.Parameter.prototype.setValue = function(value) {
  return jspb.Message.setProto3FloatField(this, 2, value);
};


/**
 * optional double state_value = 3;
 * @return {number}
 */
proto.tensorflow.data.model.ModelProto.Node.Parameter.prototype.getStateValue = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.tensorflow.data.model.ModelProto.Node.Parameter} returns this
 */
proto.tensorflow.data.model.ModelProto.Node.Parameter.prototype.setStateValue = function(value) {
  return jspb.Message.setProto3FloatField(this, 3, value);
};


/**
 * optional double min = 4;
 * @return {number}
 */
proto.tensorflow.data.model.ModelProto.Node.Parameter.prototype.getMin = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.tensorflow.data.model.ModelProto.Node.Parameter} returns this
 */
proto.tensorflow.data.model.ModelProto.Node.Parameter.prototype.setMin = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};


/**
 * optional double max = 5;
 * @return {number}
 */
proto.tensorflow.data.model.ModelProto.Node.Parameter.prototype.getMax = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 5, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.tensorflow.data.model.ModelProto.Node.Parameter} returns this
 */
proto.tensorflow.data.model.ModelProto.Node.Parameter.prototype.setMax = function(value) {
  return jspb.Message.setProto3FloatField(this, 5, value);
};


/**
 * optional bool tunable = 6;
 * @return {boolean}
 */
proto.tensorflow.data.model.ModelProto.Node.Parameter.prototype.getTunable = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 6, false));
};


/**
 * @param {boolean} value
 * @return {!proto.tensorflow.data.model.ModelProto.Node.Parameter} returns this
 */
proto.tensorflow.data.model.ModelProto.Node.Parameter.prototype.setTunable = function(value) {
  return jspb.Message.setProto3BooleanField(this, 6, value);
};


/**
 * optional int64 id = 1;
 * @return {number}
 */
proto.tensorflow.data.model.ModelProto.Node.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.tensorflow.data.model.ModelProto.Node} returns this
 */
proto.tensorflow.data.model.ModelProto.Node.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.tensorflow.data.model.ModelProto.Node.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.tensorflow.data.model.ModelProto.Node} returns this
 */
proto.tensorflow.data.model.ModelProto.Node.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional bool autotune = 3;
 * @return {boolean}
 */
proto.tensorflow.data.model.ModelProto.Node.prototype.getAutotune = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.tensorflow.data.model.ModelProto.Node} returns this
 */
proto.tensorflow.data.model.ModelProto.Node.prototype.setAutotune = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};


/**
 * optional int64 buffered_bytes = 4;
 * @return {number}
 */
proto.tensorflow.data.model.ModelProto.Node.prototype.getBufferedBytes = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.tensorflow.data.model.ModelProto.Node} returns this
 */
proto.tensorflow.data.model.ModelProto.Node.prototype.setBufferedBytes = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int64 buffered_elements = 5;
 * @return {number}
 */
proto.tensorflow.data.model.ModelProto.Node.prototype.getBufferedElements = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.tensorflow.data.model.ModelProto.Node} returns this
 */
proto.tensorflow.data.model.ModelProto.Node.prototype.setBufferedElements = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional int64 bytes_consumed = 6;
 * @return {number}
 */
proto.tensorflow.data.model.ModelProto.Node.prototype.getBytesConsumed = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.tensorflow.data.model.ModelProto.Node} returns this
 */
proto.tensorflow.data.model.ModelProto.Node.prototype.setBytesConsumed = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional int64 bytes_produced = 7;
 * @return {number}
 */
proto.tensorflow.data.model.ModelProto.Node.prototype.getBytesProduced = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.tensorflow.data.model.ModelProto.Node} returns this
 */
proto.tensorflow.data.model.ModelProto.Node.prototype.setBytesProduced = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional int64 num_elements = 8;
 * @return {number}
 */
proto.tensorflow.data.model.ModelProto.Node.prototype.getNumElements = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.tensorflow.data.model.ModelProto.Node} returns this
 */
proto.tensorflow.data.model.ModelProto.Node.prototype.setNumElements = function(value) {
  return jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * optional int64 processing_time = 9;
 * @return {number}
 */
proto.tensorflow.data.model.ModelProto.Node.prototype.getProcessingTime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {number} value
 * @return {!proto.tensorflow.data.model.ModelProto.Node} returns this
 */
proto.tensorflow.data.model.ModelProto.Node.prototype.setProcessingTime = function(value) {
  return jspb.Message.setProto3IntField(this, 9, value);
};


/**
 * optional bool record_metrics = 10;
 * @return {boolean}
 */
proto.tensorflow.data.model.ModelProto.Node.prototype.getRecordMetrics = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 10, false));
};


/**
 * @param {boolean} value
 * @return {!proto.tensorflow.data.model.ModelProto.Node} returns this
 */
proto.tensorflow.data.model.ModelProto.Node.prototype.setRecordMetrics = function(value) {
  return jspb.Message.setProto3BooleanField(this, 10, value);
};


/**
 * repeated Parameter parameters = 11;
 * @return {!Array<!proto.tensorflow.data.model.ModelProto.Node.Parameter>}
 */
proto.tensorflow.data.model.ModelProto.Node.prototype.getParametersList = function() {
  return /** @type{!Array<!proto.tensorflow.data.model.ModelProto.Node.Parameter>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.tensorflow.data.model.ModelProto.Node.Parameter, 11));
};


/**
 * @param {!Array<!proto.tensorflow.data.model.ModelProto.Node.Parameter>} value
 * @return {!proto.tensorflow.data.model.ModelProto.Node} returns this
*/
proto.tensorflow.data.model.ModelProto.Node.prototype.setParametersList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 11, value);
};


/**
 * @param {!proto.tensorflow.data.model.ModelProto.Node.Parameter=} opt_value
 * @param {number=} opt_index
 * @return {!proto.tensorflow.data.model.ModelProto.Node.Parameter}
 */
proto.tensorflow.data.model.ModelProto.Node.prototype.addParameters = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 11, opt_value, proto.tensorflow.data.model.ModelProto.Node.Parameter, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.tensorflow.data.model.ModelProto.Node} returns this
 */
proto.tensorflow.data.model.ModelProto.Node.prototype.clearParametersList = function() {
  return this.setParametersList([]);
};


/**
 * optional double input_processing_time_sum = 12;
 * @return {number}
 */
proto.tensorflow.data.model.ModelProto.Node.prototype.getInputProcessingTimeSum = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 12, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.tensorflow.data.model.ModelProto.Node} returns this
 */
proto.tensorflow.data.model.ModelProto.Node.prototype.setInputProcessingTimeSum = function(value) {
  return jspb.Message.setProto3FloatField(this, 12, value);
};


/**
 * optional int64 input_processing_time_count = 13;
 * @return {number}
 */
proto.tensorflow.data.model.ModelProto.Node.prototype.getInputProcessingTimeCount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 13, 0));
};


/**
 * @param {number} value
 * @return {!proto.tensorflow.data.model.ModelProto.Node} returns this
 */
proto.tensorflow.data.model.ModelProto.Node.prototype.setInputProcessingTimeCount = function(value) {
  return jspb.Message.setProto3IntField(this, 13, value);
};


/**
 * repeated Node inputs = 14;
 * @return {!Array<!proto.tensorflow.data.model.ModelProto.Node>}
 */
proto.tensorflow.data.model.ModelProto.Node.prototype.getInputsList = function() {
  return /** @type{!Array<!proto.tensorflow.data.model.ModelProto.Node>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.tensorflow.data.model.ModelProto.Node, 14));
};


/**
 * @param {!Array<!proto.tensorflow.data.model.ModelProto.Node>} value
 * @return {!proto.tensorflow.data.model.ModelProto.Node} returns this
*/
proto.tensorflow.data.model.ModelProto.Node.prototype.setInputsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 14, value);
};


/**
 * @param {!proto.tensorflow.data.model.ModelProto.Node=} opt_value
 * @param {number=} opt_index
 * @return {!proto.tensorflow.data.model.ModelProto.Node}
 */
proto.tensorflow.data.model.ModelProto.Node.prototype.addInputs = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 14, opt_value, proto.tensorflow.data.model.ModelProto.Node, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.tensorflow.data.model.ModelProto.Node} returns this
 */
proto.tensorflow.data.model.ModelProto.Node.prototype.clearInputsList = function() {
  return this.setInputsList([]);
};


/**
 * optional NodeClass node_class = 15;
 * @return {!proto.tensorflow.data.model.NodeClass}
 */
proto.tensorflow.data.model.ModelProto.Node.prototype.getNodeClass = function() {
  return /** @type {!proto.tensorflow.data.model.NodeClass} */ (jspb.Message.getFieldWithDefault(this, 15, 0));
};


/**
 * @param {!proto.tensorflow.data.model.NodeClass} value
 * @return {!proto.tensorflow.data.model.ModelProto.Node} returns this
 */
proto.tensorflow.data.model.ModelProto.Node.prototype.setNodeClass = function(value) {
  return jspb.Message.setProto3EnumField(this, 15, value);
};


/**
 * optional double ratio = 16;
 * @return {number}
 */
proto.tensorflow.data.model.ModelProto.Node.prototype.getRatio = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 16, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.tensorflow.data.model.ModelProto.Node} returns this
 */
proto.tensorflow.data.model.ModelProto.Node.prototype.setRatio = function(value) {
  return jspb.Message.setProto3FloatField(this, 16, value);
};


/**
 * optional double memory_ratio = 17;
 * @return {number}
 */
proto.tensorflow.data.model.ModelProto.Node.prototype.getMemoryRatio = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 17, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.tensorflow.data.model.ModelProto.Node} returns this
 */
proto.tensorflow.data.model.ModelProto.Node.prototype.setMemoryRatio = function(value) {
  return jspb.Message.setProto3FloatField(this, 17, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tensorflow.data.model.ModelProto.OptimizationParams.prototype.toObject = function(opt_includeInstance) {
  return proto.tensorflow.data.model.ModelProto.OptimizationParams.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tensorflow.data.model.ModelProto.OptimizationParams} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tensorflow.data.model.ModelProto.OptimizationParams.toObject = function(includeInstance, msg) {
  var f, obj = {
    algorithm: jspb.Message.getFieldWithDefault(msg, 1, 0),
    cpuBudget: jspb.Message.getFieldWithDefault(msg, 2, 0),
    ramBudget: jspb.Message.getFieldWithDefault(msg, 3, 0),
    modelInputTime: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tensorflow.data.model.ModelProto.OptimizationParams}
 */
proto.tensorflow.data.model.ModelProto.OptimizationParams.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tensorflow.data.model.ModelProto.OptimizationParams;
  return proto.tensorflow.data.model.ModelProto.OptimizationParams.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tensorflow.data.model.ModelProto.OptimizationParams} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tensorflow.data.model.ModelProto.OptimizationParams}
 */
proto.tensorflow.data.model.ModelProto.OptimizationParams.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.tensorflow.data.model.AutotuneAlgorithm} */ (reader.readEnum());
      msg.setAlgorithm(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCpuBudget(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setRamBudget(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setModelInputTime(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tensorflow.data.model.ModelProto.OptimizationParams.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tensorflow.data.model.ModelProto.OptimizationParams.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tensorflow.data.model.ModelProto.OptimizationParams} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tensorflow.data.model.ModelProto.OptimizationParams.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAlgorithm();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getCpuBudget();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getRamBudget();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = message.getModelInputTime();
  if (f !== 0.0) {
    writer.writeDouble(
      4,
      f
    );
  }
};


/**
 * optional AutotuneAlgorithm algorithm = 1;
 * @return {!proto.tensorflow.data.model.AutotuneAlgorithm}
 */
proto.tensorflow.data.model.ModelProto.OptimizationParams.prototype.getAlgorithm = function() {
  return /** @type {!proto.tensorflow.data.model.AutotuneAlgorithm} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.tensorflow.data.model.AutotuneAlgorithm} value
 * @return {!proto.tensorflow.data.model.ModelProto.OptimizationParams} returns this
 */
proto.tensorflow.data.model.ModelProto.OptimizationParams.prototype.setAlgorithm = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional int64 cpu_budget = 2;
 * @return {number}
 */
proto.tensorflow.data.model.ModelProto.OptimizationParams.prototype.getCpuBudget = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.tensorflow.data.model.ModelProto.OptimizationParams} returns this
 */
proto.tensorflow.data.model.ModelProto.OptimizationParams.prototype.setCpuBudget = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int64 ram_budget = 3;
 * @return {number}
 */
proto.tensorflow.data.model.ModelProto.OptimizationParams.prototype.getRamBudget = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.tensorflow.data.model.ModelProto.OptimizationParams} returns this
 */
proto.tensorflow.data.model.ModelProto.OptimizationParams.prototype.setRamBudget = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional double model_input_time = 4;
 * @return {number}
 */
proto.tensorflow.data.model.ModelProto.OptimizationParams.prototype.getModelInputTime = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.tensorflow.data.model.ModelProto.OptimizationParams} returns this
 */
proto.tensorflow.data.model.ModelProto.OptimizationParams.prototype.setModelInputTime = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};


/**
 * optional Node output = 1;
 * @return {?proto.tensorflow.data.model.ModelProto.Node}
 */
proto.tensorflow.data.model.ModelProto.prototype.getOutput = function() {
  return /** @type{?proto.tensorflow.data.model.ModelProto.Node} */ (
    jspb.Message.getWrapperField(this, proto.tensorflow.data.model.ModelProto.Node, 1));
};


/**
 * @param {?proto.tensorflow.data.model.ModelProto.Node|undefined} value
 * @return {!proto.tensorflow.data.model.ModelProto} returns this
*/
proto.tensorflow.data.model.ModelProto.prototype.setOutput = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.tensorflow.data.model.ModelProto} returns this
 */
proto.tensorflow.data.model.ModelProto.prototype.clearOutput = function() {
  return this.setOutput(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tensorflow.data.model.ModelProto.prototype.hasOutput = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional int64 id_counter = 2;
 * @return {number}
 */
proto.tensorflow.data.model.ModelProto.prototype.getIdCounter = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.tensorflow.data.model.ModelProto} returns this
 */
proto.tensorflow.data.model.ModelProto.prototype.setIdCounter = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional bool collect_resource_usage = 3;
 * @return {boolean}
 */
proto.tensorflow.data.model.ModelProto.prototype.getCollectResourceUsage = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.tensorflow.data.model.ModelProto} returns this
 */
proto.tensorflow.data.model.ModelProto.prototype.setCollectResourceUsage = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};


/**
 * optional OptimizationParams optimization_params = 4;
 * @return {?proto.tensorflow.data.model.ModelProto.OptimizationParams}
 */
proto.tensorflow.data.model.ModelProto.prototype.getOptimizationParams = function() {
  return /** @type{?proto.tensorflow.data.model.ModelProto.OptimizationParams} */ (
    jspb.Message.getWrapperField(this, proto.tensorflow.data.model.ModelProto.OptimizationParams, 4));
};


/**
 * @param {?proto.tensorflow.data.model.ModelProto.OptimizationParams|undefined} value
 * @return {!proto.tensorflow.data.model.ModelProto} returns this
*/
proto.tensorflow.data.model.ModelProto.prototype.setOptimizationParams = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.tensorflow.data.model.ModelProto} returns this
 */
proto.tensorflow.data.model.ModelProto.prototype.clearOptimizationParams = function() {
  return this.setOptimizationParams(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tensorflow.data.model.ModelProto.prototype.hasOptimizationParams = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * @enum {number}
 */
proto.tensorflow.data.model.NodeClass = {
  UNKNOWN: 0,
  INTERLEAVE_MANY: 1,
  ASYNC_INTERLEAVE_MANY: 2,
  KNOWN_RATIO: 3,
  ASYNC_KNOWN_RATIO: 4,
  UNKNOWN_RATIO: 5
};

/**
 * @enum {number}
 */
proto.tensorflow.data.model.AutotuneAlgorithm = {
  HILL_CLIMB: 0,
  GRADIENT_DESCENT: 1
};

goog.object.extend(exports, proto.tensorflow.data.model);
