// source: tensorflow/core/protobuf/composite_tensor_variant.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var tensorflow_core_protobuf_struct_pb = require('../../../tensorflow/core/protobuf/struct_pb.js');
goog.object.extend(proto, tensorflow_core_protobuf_struct_pb);
goog.exportSymbol('proto.tensorflow.CompositeTensorVariantMetadata', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tensorflow.CompositeTensorVariantMetadata = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.tensorflow.CompositeTensorVariantMetadata, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.tensorflow.CompositeTensorVariantMetadata.displayName = 'proto.tensorflow.CompositeTensorVariantMetadata';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tensorflow.CompositeTensorVariantMetadata.prototype.toObject = function(opt_includeInstance) {
  return proto.tensorflow.CompositeTensorVariantMetadata.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tensorflow.CompositeTensorVariantMetadata} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tensorflow.CompositeTensorVariantMetadata.toObject = function(includeInstance, msg) {
  var f, obj = {
    typeSpecProto: (f = msg.getTypeSpecProto()) && tensorflow_core_protobuf_struct_pb.TypeSpecProto.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tensorflow.CompositeTensorVariantMetadata}
 */
proto.tensorflow.CompositeTensorVariantMetadata.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tensorflow.CompositeTensorVariantMetadata;
  return proto.tensorflow.CompositeTensorVariantMetadata.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tensorflow.CompositeTensorVariantMetadata} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tensorflow.CompositeTensorVariantMetadata}
 */
proto.tensorflow.CompositeTensorVariantMetadata.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new tensorflow_core_protobuf_struct_pb.TypeSpecProto;
      reader.readMessage(value,tensorflow_core_protobuf_struct_pb.TypeSpecProto.deserializeBinaryFromReader);
      msg.setTypeSpecProto(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tensorflow.CompositeTensorVariantMetadata.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tensorflow.CompositeTensorVariantMetadata.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tensorflow.CompositeTensorVariantMetadata} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tensorflow.CompositeTensorVariantMetadata.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTypeSpecProto();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      tensorflow_core_protobuf_struct_pb.TypeSpecProto.serializeBinaryToWriter
    );
  }
};


/**
 * optional TypeSpecProto type_spec_proto = 1;
 * @return {?proto.tensorflow.TypeSpecProto}
 */
proto.tensorflow.CompositeTensorVariantMetadata.prototype.getTypeSpecProto = function() {
  return /** @type{?proto.tensorflow.TypeSpecProto} */ (
    jspb.Message.getWrapperField(this, tensorflow_core_protobuf_struct_pb.TypeSpecProto, 1));
};


/**
 * @param {?proto.tensorflow.TypeSpecProto|undefined} value
 * @return {!proto.tensorflow.CompositeTensorVariantMetadata} returns this
*/
proto.tensorflow.CompositeTensorVariantMetadata.prototype.setTypeSpecProto = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.tensorflow.CompositeTensorVariantMetadata} returns this
 */
proto.tensorflow.CompositeTensorVariantMetadata.prototype.clearTypeSpecProto = function() {
  return this.setTypeSpecProto(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tensorflow.CompositeTensorVariantMetadata.prototype.hasTypeSpecProto = function() {
  return jspb.Message.getField(this, 1) != null;
};


goog.object.extend(exports, proto.tensorflow);
