// source: tensorflow/core/protobuf/remote_tensor_handle.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var tensorflow_core_framework_tensor_shape_pb = require('../../../tensorflow/core/framework/tensor_shape_pb.js');
goog.object.extend(proto, tensorflow_core_framework_tensor_shape_pb);
var tensorflow_core_framework_types_pb = require('../../../tensorflow/core/framework/types_pb.js');
goog.object.extend(proto, tensorflow_core_framework_types_pb);
goog.exportSymbol('proto.tensorflow.eager.RemoteTensorHandle', null, global);
goog.exportSymbol('proto.tensorflow.eager.ResourceDtypeAndShape', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tensorflow.eager.ResourceDtypeAndShape = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.tensorflow.eager.ResourceDtypeAndShape, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.tensorflow.eager.ResourceDtypeAndShape.displayName = 'proto.tensorflow.eager.ResourceDtypeAndShape';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tensorflow.eager.RemoteTensorHandle = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.tensorflow.eager.RemoteTensorHandle.repeatedFields_, null);
};
goog.inherits(proto.tensorflow.eager.RemoteTensorHandle, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.tensorflow.eager.RemoteTensorHandle.displayName = 'proto.tensorflow.eager.RemoteTensorHandle';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tensorflow.eager.ResourceDtypeAndShape.prototype.toObject = function(opt_includeInstance) {
  return proto.tensorflow.eager.ResourceDtypeAndShape.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tensorflow.eager.ResourceDtypeAndShape} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tensorflow.eager.ResourceDtypeAndShape.toObject = function(includeInstance, msg) {
  var f, obj = {
    dtype: jspb.Message.getFieldWithDefault(msg, 1, 0),
    shape: (f = msg.getShape()) && tensorflow_core_framework_tensor_shape_pb.TensorShapeProto.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tensorflow.eager.ResourceDtypeAndShape}
 */
proto.tensorflow.eager.ResourceDtypeAndShape.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tensorflow.eager.ResourceDtypeAndShape;
  return proto.tensorflow.eager.ResourceDtypeAndShape.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tensorflow.eager.ResourceDtypeAndShape} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tensorflow.eager.ResourceDtypeAndShape}
 */
proto.tensorflow.eager.ResourceDtypeAndShape.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.tensorflow.DataType} */ (reader.readEnum());
      msg.setDtype(value);
      break;
    case 2:
      var value = new tensorflow_core_framework_tensor_shape_pb.TensorShapeProto;
      reader.readMessage(value,tensorflow_core_framework_tensor_shape_pb.TensorShapeProto.deserializeBinaryFromReader);
      msg.setShape(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tensorflow.eager.ResourceDtypeAndShape.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tensorflow.eager.ResourceDtypeAndShape.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tensorflow.eager.ResourceDtypeAndShape} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tensorflow.eager.ResourceDtypeAndShape.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDtype();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getShape();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      tensorflow_core_framework_tensor_shape_pb.TensorShapeProto.serializeBinaryToWriter
    );
  }
};


/**
 * optional tensorflow.DataType dtype = 1;
 * @return {!proto.tensorflow.DataType}
 */
proto.tensorflow.eager.ResourceDtypeAndShape.prototype.getDtype = function() {
  return /** @type {!proto.tensorflow.DataType} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.tensorflow.DataType} value
 * @return {!proto.tensorflow.eager.ResourceDtypeAndShape} returns this
 */
proto.tensorflow.eager.ResourceDtypeAndShape.prototype.setDtype = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional tensorflow.TensorShapeProto shape = 2;
 * @return {?proto.tensorflow.TensorShapeProto}
 */
proto.tensorflow.eager.ResourceDtypeAndShape.prototype.getShape = function() {
  return /** @type{?proto.tensorflow.TensorShapeProto} */ (
    jspb.Message.getWrapperField(this, tensorflow_core_framework_tensor_shape_pb.TensorShapeProto, 2));
};


/**
 * @param {?proto.tensorflow.TensorShapeProto|undefined} value
 * @return {!proto.tensorflow.eager.ResourceDtypeAndShape} returns this
*/
proto.tensorflow.eager.ResourceDtypeAndShape.prototype.setShape = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.tensorflow.eager.ResourceDtypeAndShape} returns this
 */
proto.tensorflow.eager.ResourceDtypeAndShape.prototype.clearShape = function() {
  return this.setShape(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tensorflow.eager.ResourceDtypeAndShape.prototype.hasShape = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.tensorflow.eager.RemoteTensorHandle.repeatedFields_ = [6];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tensorflow.eager.RemoteTensorHandle.prototype.toObject = function(opt_includeInstance) {
  return proto.tensorflow.eager.RemoteTensorHandle.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tensorflow.eager.RemoteTensorHandle} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tensorflow.eager.RemoteTensorHandle.toObject = function(includeInstance, msg) {
  var f, obj = {
    opId: jspb.Message.getFieldWithDefault(msg, 1, 0),
    outputNum: jspb.Message.getFieldWithDefault(msg, 2, 0),
    device: jspb.Message.getFieldWithDefault(msg, 3, ""),
    opDevice: jspb.Message.getFieldWithDefault(msg, 4, ""),
    dtype: jspb.Message.getFieldWithDefault(msg, 5, 0),
    resourceDtypesAndShapesList: jspb.Message.toObjectList(msg.getResourceDtypesAndShapesList(),
    proto.tensorflow.eager.ResourceDtypeAndShape.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tensorflow.eager.RemoteTensorHandle}
 */
proto.tensorflow.eager.RemoteTensorHandle.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tensorflow.eager.RemoteTensorHandle;
  return proto.tensorflow.eager.RemoteTensorHandle.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tensorflow.eager.RemoteTensorHandle} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tensorflow.eager.RemoteTensorHandle}
 */
proto.tensorflow.eager.RemoteTensorHandle.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setOpId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setOutputNum(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setDevice(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setOpDevice(value);
      break;
    case 5:
      var value = /** @type {!proto.tensorflow.DataType} */ (reader.readEnum());
      msg.setDtype(value);
      break;
    case 6:
      var value = new proto.tensorflow.eager.ResourceDtypeAndShape;
      reader.readMessage(value,proto.tensorflow.eager.ResourceDtypeAndShape.deserializeBinaryFromReader);
      msg.addResourceDtypesAndShapes(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tensorflow.eager.RemoteTensorHandle.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tensorflow.eager.RemoteTensorHandle.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tensorflow.eager.RemoteTensorHandle} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tensorflow.eager.RemoteTensorHandle.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOpId();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getOutputNum();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getDevice();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getOpDevice();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getDtype();
  if (f !== 0.0) {
    writer.writeEnum(
      5,
      f
    );
  }
  f = message.getResourceDtypesAndShapesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      6,
      f,
      proto.tensorflow.eager.ResourceDtypeAndShape.serializeBinaryToWriter
    );
  }
};


/**
 * optional int64 op_id = 1;
 * @return {number}
 */
proto.tensorflow.eager.RemoteTensorHandle.prototype.getOpId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.tensorflow.eager.RemoteTensorHandle} returns this
 */
proto.tensorflow.eager.RemoteTensorHandle.prototype.setOpId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 output_num = 2;
 * @return {number}
 */
proto.tensorflow.eager.RemoteTensorHandle.prototype.getOutputNum = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.tensorflow.eager.RemoteTensorHandle} returns this
 */
proto.tensorflow.eager.RemoteTensorHandle.prototype.setOutputNum = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string device = 3;
 * @return {string}
 */
proto.tensorflow.eager.RemoteTensorHandle.prototype.getDevice = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.tensorflow.eager.RemoteTensorHandle} returns this
 */
proto.tensorflow.eager.RemoteTensorHandle.prototype.setDevice = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string op_device = 4;
 * @return {string}
 */
proto.tensorflow.eager.RemoteTensorHandle.prototype.getOpDevice = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.tensorflow.eager.RemoteTensorHandle} returns this
 */
proto.tensorflow.eager.RemoteTensorHandle.prototype.setOpDevice = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional tensorflow.DataType dtype = 5;
 * @return {!proto.tensorflow.DataType}
 */
proto.tensorflow.eager.RemoteTensorHandle.prototype.getDtype = function() {
  return /** @type {!proto.tensorflow.DataType} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {!proto.tensorflow.DataType} value
 * @return {!proto.tensorflow.eager.RemoteTensorHandle} returns this
 */
proto.tensorflow.eager.RemoteTensorHandle.prototype.setDtype = function(value) {
  return jspb.Message.setProto3EnumField(this, 5, value);
};


/**
 * repeated ResourceDtypeAndShape resource_dtypes_and_shapes = 6;
 * @return {!Array<!proto.tensorflow.eager.ResourceDtypeAndShape>}
 */
proto.tensorflow.eager.RemoteTensorHandle.prototype.getResourceDtypesAndShapesList = function() {
  return /** @type{!Array<!proto.tensorflow.eager.ResourceDtypeAndShape>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.tensorflow.eager.ResourceDtypeAndShape, 6));
};


/**
 * @param {!Array<!proto.tensorflow.eager.ResourceDtypeAndShape>} value
 * @return {!proto.tensorflow.eager.RemoteTensorHandle} returns this
*/
proto.tensorflow.eager.RemoteTensorHandle.prototype.setResourceDtypesAndShapesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 6, value);
};


/**
 * @param {!proto.tensorflow.eager.ResourceDtypeAndShape=} opt_value
 * @param {number=} opt_index
 * @return {!proto.tensorflow.eager.ResourceDtypeAndShape}
 */
proto.tensorflow.eager.RemoteTensorHandle.prototype.addResourceDtypesAndShapes = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 6, opt_value, proto.tensorflow.eager.ResourceDtypeAndShape, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.tensorflow.eager.RemoteTensorHandle} returns this
 */
proto.tensorflow.eager.RemoteTensorHandle.prototype.clearResourceDtypesAndShapesList = function() {
  return this.setResourceDtypesAndShapesList([]);
};


goog.object.extend(exports, proto.tensorflow.eager);
