// source: tensorflow/core/protobuf/replay_log.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var tensorflow_core_protobuf_master_pb = require('../../../tensorflow/core/protobuf/master_pb.js');
goog.object.extend(proto, tensorflow_core_protobuf_master_pb);
goog.exportSymbol('proto.tensorflow.NewReplaySession', null, global);
goog.exportSymbol('proto.tensorflow.ReplayOp', null, global);
goog.exportSymbol('proto.tensorflow.ReplayOp.OpCase', null, global);
goog.exportSymbol('proto.tensorflow.ReplayOp.ResponseCase', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tensorflow.NewReplaySession = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.tensorflow.NewReplaySession, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.tensorflow.NewReplaySession.displayName = 'proto.tensorflow.NewReplaySession';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tensorflow.ReplayOp = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.tensorflow.ReplayOp.oneofGroups_);
};
goog.inherits(proto.tensorflow.ReplayOp, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.tensorflow.ReplayOp.displayName = 'proto.tensorflow.ReplayOp';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tensorflow.NewReplaySession.prototype.toObject = function(opt_includeInstance) {
  return proto.tensorflow.NewReplaySession.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tensorflow.NewReplaySession} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tensorflow.NewReplaySession.toObject = function(includeInstance, msg) {
  var f, obj = {
    devices: (f = msg.getDevices()) && tensorflow_core_protobuf_master_pb.ListDevicesResponse.toObject(includeInstance, f),
    sessionHandle: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tensorflow.NewReplaySession}
 */
proto.tensorflow.NewReplaySession.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tensorflow.NewReplaySession;
  return proto.tensorflow.NewReplaySession.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tensorflow.NewReplaySession} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tensorflow.NewReplaySession}
 */
proto.tensorflow.NewReplaySession.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new tensorflow_core_protobuf_master_pb.ListDevicesResponse;
      reader.readMessage(value,tensorflow_core_protobuf_master_pb.ListDevicesResponse.deserializeBinaryFromReader);
      msg.setDevices(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setSessionHandle(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tensorflow.NewReplaySession.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tensorflow.NewReplaySession.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tensorflow.NewReplaySession} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tensorflow.NewReplaySession.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDevices();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      tensorflow_core_protobuf_master_pb.ListDevicesResponse.serializeBinaryToWriter
    );
  }
  f = message.getSessionHandle();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional ListDevicesResponse devices = 1;
 * @return {?proto.tensorflow.ListDevicesResponse}
 */
proto.tensorflow.NewReplaySession.prototype.getDevices = function() {
  return /** @type{?proto.tensorflow.ListDevicesResponse} */ (
    jspb.Message.getWrapperField(this, tensorflow_core_protobuf_master_pb.ListDevicesResponse, 1));
};


/**
 * @param {?proto.tensorflow.ListDevicesResponse|undefined} value
 * @return {!proto.tensorflow.NewReplaySession} returns this
*/
proto.tensorflow.NewReplaySession.prototype.setDevices = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.tensorflow.NewReplaySession} returns this
 */
proto.tensorflow.NewReplaySession.prototype.clearDevices = function() {
  return this.setDevices(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tensorflow.NewReplaySession.prototype.hasDevices = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string session_handle = 2;
 * @return {string}
 */
proto.tensorflow.NewReplaySession.prototype.getSessionHandle = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.tensorflow.NewReplaySession} returns this
 */
proto.tensorflow.NewReplaySession.prototype.setSessionHandle = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.tensorflow.ReplayOp.oneofGroups_ = [[1,2,3,4,5,6,7,8,9,10,11],[21,22,23,24,25,26,27,28,29,30]];

/**
 * @enum {number}
 */
proto.tensorflow.ReplayOp.OpCase = {
  OP_NOT_SET: 0,
  CREATE_SESSION: 1,
  EXTEND_SESSION: 2,
  PARTIAL_RUN_SETUP: 3,
  RUN_STEP: 4,
  CLOSE_SESSION: 5,
  LIST_DEVICES: 6,
  RESET_REQUEST: 7,
  MAKE_CALLABLE: 8,
  RUN_CALLABLE: 9,
  RELEASE_CALLABLE: 10,
  NEW_REPLAY_SESSION: 11
};

/**
 * @return {proto.tensorflow.ReplayOp.OpCase}
 */
proto.tensorflow.ReplayOp.prototype.getOpCase = function() {
  return /** @type {proto.tensorflow.ReplayOp.OpCase} */(jspb.Message.computeOneofCase(this, proto.tensorflow.ReplayOp.oneofGroups_[0]));
};

/**
 * @enum {number}
 */
proto.tensorflow.ReplayOp.ResponseCase = {
  RESPONSE_NOT_SET: 0,
  CREATE_SESSION_RESPONSE: 21,
  EXTEND_SESSION_RESPONSE: 22,
  PARTIAL_RUN_SETUP_RESPONSE: 23,
  RUN_STEP_RESPONSE: 24,
  CLOSE_SESSION_RESPONSE: 25,
  LIST_DEVICES_RESPONSE: 26,
  RESET_REQUEST_RESPONSE: 27,
  MAKE_CALLABLE_RESPONSE: 28,
  RUN_CALLABLE_RESPONSE: 29,
  RELEASE_CALLABLE_RESPONSE: 30
};

/**
 * @return {proto.tensorflow.ReplayOp.ResponseCase}
 */
proto.tensorflow.ReplayOp.prototype.getResponseCase = function() {
  return /** @type {proto.tensorflow.ReplayOp.ResponseCase} */(jspb.Message.computeOneofCase(this, proto.tensorflow.ReplayOp.oneofGroups_[1]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tensorflow.ReplayOp.prototype.toObject = function(opt_includeInstance) {
  return proto.tensorflow.ReplayOp.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tensorflow.ReplayOp} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tensorflow.ReplayOp.toObject = function(includeInstance, msg) {
  var f, obj = {
    startTimeUs: jspb.Message.getFloatingPointFieldWithDefault(msg, 31, 0.0),
    endTimeUs: jspb.Message.getFloatingPointFieldWithDefault(msg, 32, 0.0),
    createSession: (f = msg.getCreateSession()) && tensorflow_core_protobuf_master_pb.CreateSessionRequest.toObject(includeInstance, f),
    extendSession: (f = msg.getExtendSession()) && tensorflow_core_protobuf_master_pb.ExtendSessionRequest.toObject(includeInstance, f),
    partialRunSetup: (f = msg.getPartialRunSetup()) && tensorflow_core_protobuf_master_pb.PartialRunSetupRequest.toObject(includeInstance, f),
    runStep: (f = msg.getRunStep()) && tensorflow_core_protobuf_master_pb.RunStepRequest.toObject(includeInstance, f),
    closeSession: (f = msg.getCloseSession()) && tensorflow_core_protobuf_master_pb.CloseSessionRequest.toObject(includeInstance, f),
    listDevices: (f = msg.getListDevices()) && tensorflow_core_protobuf_master_pb.ListDevicesRequest.toObject(includeInstance, f),
    resetRequest: (f = msg.getResetRequest()) && tensorflow_core_protobuf_master_pb.ResetRequest.toObject(includeInstance, f),
    makeCallable: (f = msg.getMakeCallable()) && tensorflow_core_protobuf_master_pb.MakeCallableRequest.toObject(includeInstance, f),
    runCallable: (f = msg.getRunCallable()) && tensorflow_core_protobuf_master_pb.RunCallableRequest.toObject(includeInstance, f),
    releaseCallable: (f = msg.getReleaseCallable()) && tensorflow_core_protobuf_master_pb.ReleaseCallableRequest.toObject(includeInstance, f),
    newReplaySession: (f = msg.getNewReplaySession()) && proto.tensorflow.NewReplaySession.toObject(includeInstance, f),
    createSessionResponse: (f = msg.getCreateSessionResponse()) && tensorflow_core_protobuf_master_pb.CreateSessionResponse.toObject(includeInstance, f),
    extendSessionResponse: (f = msg.getExtendSessionResponse()) && tensorflow_core_protobuf_master_pb.ExtendSessionResponse.toObject(includeInstance, f),
    partialRunSetupResponse: (f = msg.getPartialRunSetupResponse()) && tensorflow_core_protobuf_master_pb.PartialRunSetupResponse.toObject(includeInstance, f),
    runStepResponse: (f = msg.getRunStepResponse()) && tensorflow_core_protobuf_master_pb.RunStepResponse.toObject(includeInstance, f),
    closeSessionResponse: (f = msg.getCloseSessionResponse()) && tensorflow_core_protobuf_master_pb.CloseSessionResponse.toObject(includeInstance, f),
    listDevicesResponse: (f = msg.getListDevicesResponse()) && tensorflow_core_protobuf_master_pb.ListDevicesResponse.toObject(includeInstance, f),
    resetRequestResponse: (f = msg.getResetRequestResponse()) && tensorflow_core_protobuf_master_pb.ResetResponse.toObject(includeInstance, f),
    makeCallableResponse: (f = msg.getMakeCallableResponse()) && tensorflow_core_protobuf_master_pb.MakeCallableResponse.toObject(includeInstance, f),
    runCallableResponse: (f = msg.getRunCallableResponse()) && tensorflow_core_protobuf_master_pb.RunCallableResponse.toObject(includeInstance, f),
    releaseCallableResponse: (f = msg.getReleaseCallableResponse()) && tensorflow_core_protobuf_master_pb.ReleaseCallableResponse.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tensorflow.ReplayOp}
 */
proto.tensorflow.ReplayOp.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tensorflow.ReplayOp;
  return proto.tensorflow.ReplayOp.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tensorflow.ReplayOp} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tensorflow.ReplayOp}
 */
proto.tensorflow.ReplayOp.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 31:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setStartTimeUs(value);
      break;
    case 32:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setEndTimeUs(value);
      break;
    case 1:
      var value = new tensorflow_core_protobuf_master_pb.CreateSessionRequest;
      reader.readMessage(value,tensorflow_core_protobuf_master_pb.CreateSessionRequest.deserializeBinaryFromReader);
      msg.setCreateSession(value);
      break;
    case 2:
      var value = new tensorflow_core_protobuf_master_pb.ExtendSessionRequest;
      reader.readMessage(value,tensorflow_core_protobuf_master_pb.ExtendSessionRequest.deserializeBinaryFromReader);
      msg.setExtendSession(value);
      break;
    case 3:
      var value = new tensorflow_core_protobuf_master_pb.PartialRunSetupRequest;
      reader.readMessage(value,tensorflow_core_protobuf_master_pb.PartialRunSetupRequest.deserializeBinaryFromReader);
      msg.setPartialRunSetup(value);
      break;
    case 4:
      var value = new tensorflow_core_protobuf_master_pb.RunStepRequest;
      reader.readMessage(value,tensorflow_core_protobuf_master_pb.RunStepRequest.deserializeBinaryFromReader);
      msg.setRunStep(value);
      break;
    case 5:
      var value = new tensorflow_core_protobuf_master_pb.CloseSessionRequest;
      reader.readMessage(value,tensorflow_core_protobuf_master_pb.CloseSessionRequest.deserializeBinaryFromReader);
      msg.setCloseSession(value);
      break;
    case 6:
      var value = new tensorflow_core_protobuf_master_pb.ListDevicesRequest;
      reader.readMessage(value,tensorflow_core_protobuf_master_pb.ListDevicesRequest.deserializeBinaryFromReader);
      msg.setListDevices(value);
      break;
    case 7:
      var value = new tensorflow_core_protobuf_master_pb.ResetRequest;
      reader.readMessage(value,tensorflow_core_protobuf_master_pb.ResetRequest.deserializeBinaryFromReader);
      msg.setResetRequest(value);
      break;
    case 8:
      var value = new tensorflow_core_protobuf_master_pb.MakeCallableRequest;
      reader.readMessage(value,tensorflow_core_protobuf_master_pb.MakeCallableRequest.deserializeBinaryFromReader);
      msg.setMakeCallable(value);
      break;
    case 9:
      var value = new tensorflow_core_protobuf_master_pb.RunCallableRequest;
      reader.readMessage(value,tensorflow_core_protobuf_master_pb.RunCallableRequest.deserializeBinaryFromReader);
      msg.setRunCallable(value);
      break;
    case 10:
      var value = new tensorflow_core_protobuf_master_pb.ReleaseCallableRequest;
      reader.readMessage(value,tensorflow_core_protobuf_master_pb.ReleaseCallableRequest.deserializeBinaryFromReader);
      msg.setReleaseCallable(value);
      break;
    case 11:
      var value = new proto.tensorflow.NewReplaySession;
      reader.readMessage(value,proto.tensorflow.NewReplaySession.deserializeBinaryFromReader);
      msg.setNewReplaySession(value);
      break;
    case 21:
      var value = new tensorflow_core_protobuf_master_pb.CreateSessionResponse;
      reader.readMessage(value,tensorflow_core_protobuf_master_pb.CreateSessionResponse.deserializeBinaryFromReader);
      msg.setCreateSessionResponse(value);
      break;
    case 22:
      var value = new tensorflow_core_protobuf_master_pb.ExtendSessionResponse;
      reader.readMessage(value,tensorflow_core_protobuf_master_pb.ExtendSessionResponse.deserializeBinaryFromReader);
      msg.setExtendSessionResponse(value);
      break;
    case 23:
      var value = new tensorflow_core_protobuf_master_pb.PartialRunSetupResponse;
      reader.readMessage(value,tensorflow_core_protobuf_master_pb.PartialRunSetupResponse.deserializeBinaryFromReader);
      msg.setPartialRunSetupResponse(value);
      break;
    case 24:
      var value = new tensorflow_core_protobuf_master_pb.RunStepResponse;
      reader.readMessage(value,tensorflow_core_protobuf_master_pb.RunStepResponse.deserializeBinaryFromReader);
      msg.setRunStepResponse(value);
      break;
    case 25:
      var value = new tensorflow_core_protobuf_master_pb.CloseSessionResponse;
      reader.readMessage(value,tensorflow_core_protobuf_master_pb.CloseSessionResponse.deserializeBinaryFromReader);
      msg.setCloseSessionResponse(value);
      break;
    case 26:
      var value = new tensorflow_core_protobuf_master_pb.ListDevicesResponse;
      reader.readMessage(value,tensorflow_core_protobuf_master_pb.ListDevicesResponse.deserializeBinaryFromReader);
      msg.setListDevicesResponse(value);
      break;
    case 27:
      var value = new tensorflow_core_protobuf_master_pb.ResetResponse;
      reader.readMessage(value,tensorflow_core_protobuf_master_pb.ResetResponse.deserializeBinaryFromReader);
      msg.setResetRequestResponse(value);
      break;
    case 28:
      var value = new tensorflow_core_protobuf_master_pb.MakeCallableResponse;
      reader.readMessage(value,tensorflow_core_protobuf_master_pb.MakeCallableResponse.deserializeBinaryFromReader);
      msg.setMakeCallableResponse(value);
      break;
    case 29:
      var value = new tensorflow_core_protobuf_master_pb.RunCallableResponse;
      reader.readMessage(value,tensorflow_core_protobuf_master_pb.RunCallableResponse.deserializeBinaryFromReader);
      msg.setRunCallableResponse(value);
      break;
    case 30:
      var value = new tensorflow_core_protobuf_master_pb.ReleaseCallableResponse;
      reader.readMessage(value,tensorflow_core_protobuf_master_pb.ReleaseCallableResponse.deserializeBinaryFromReader);
      msg.setReleaseCallableResponse(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tensorflow.ReplayOp.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tensorflow.ReplayOp.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tensorflow.ReplayOp} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tensorflow.ReplayOp.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStartTimeUs();
  if (f !== 0.0) {
    writer.writeDouble(
      31,
      f
    );
  }
  f = message.getEndTimeUs();
  if (f !== 0.0) {
    writer.writeDouble(
      32,
      f
    );
  }
  f = message.getCreateSession();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      tensorflow_core_protobuf_master_pb.CreateSessionRequest.serializeBinaryToWriter
    );
  }
  f = message.getExtendSession();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      tensorflow_core_protobuf_master_pb.ExtendSessionRequest.serializeBinaryToWriter
    );
  }
  f = message.getPartialRunSetup();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      tensorflow_core_protobuf_master_pb.PartialRunSetupRequest.serializeBinaryToWriter
    );
  }
  f = message.getRunStep();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      tensorflow_core_protobuf_master_pb.RunStepRequest.serializeBinaryToWriter
    );
  }
  f = message.getCloseSession();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      tensorflow_core_protobuf_master_pb.CloseSessionRequest.serializeBinaryToWriter
    );
  }
  f = message.getListDevices();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      tensorflow_core_protobuf_master_pb.ListDevicesRequest.serializeBinaryToWriter
    );
  }
  f = message.getResetRequest();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      tensorflow_core_protobuf_master_pb.ResetRequest.serializeBinaryToWriter
    );
  }
  f = message.getMakeCallable();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      tensorflow_core_protobuf_master_pb.MakeCallableRequest.serializeBinaryToWriter
    );
  }
  f = message.getRunCallable();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      tensorflow_core_protobuf_master_pb.RunCallableRequest.serializeBinaryToWriter
    );
  }
  f = message.getReleaseCallable();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      tensorflow_core_protobuf_master_pb.ReleaseCallableRequest.serializeBinaryToWriter
    );
  }
  f = message.getNewReplaySession();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      proto.tensorflow.NewReplaySession.serializeBinaryToWriter
    );
  }
  f = message.getCreateSessionResponse();
  if (f != null) {
    writer.writeMessage(
      21,
      f,
      tensorflow_core_protobuf_master_pb.CreateSessionResponse.serializeBinaryToWriter
    );
  }
  f = message.getExtendSessionResponse();
  if (f != null) {
    writer.writeMessage(
      22,
      f,
      tensorflow_core_protobuf_master_pb.ExtendSessionResponse.serializeBinaryToWriter
    );
  }
  f = message.getPartialRunSetupResponse();
  if (f != null) {
    writer.writeMessage(
      23,
      f,
      tensorflow_core_protobuf_master_pb.PartialRunSetupResponse.serializeBinaryToWriter
    );
  }
  f = message.getRunStepResponse();
  if (f != null) {
    writer.writeMessage(
      24,
      f,
      tensorflow_core_protobuf_master_pb.RunStepResponse.serializeBinaryToWriter
    );
  }
  f = message.getCloseSessionResponse();
  if (f != null) {
    writer.writeMessage(
      25,
      f,
      tensorflow_core_protobuf_master_pb.CloseSessionResponse.serializeBinaryToWriter
    );
  }
  f = message.getListDevicesResponse();
  if (f != null) {
    writer.writeMessage(
      26,
      f,
      tensorflow_core_protobuf_master_pb.ListDevicesResponse.serializeBinaryToWriter
    );
  }
  f = message.getResetRequestResponse();
  if (f != null) {
    writer.writeMessage(
      27,
      f,
      tensorflow_core_protobuf_master_pb.ResetResponse.serializeBinaryToWriter
    );
  }
  f = message.getMakeCallableResponse();
  if (f != null) {
    writer.writeMessage(
      28,
      f,
      tensorflow_core_protobuf_master_pb.MakeCallableResponse.serializeBinaryToWriter
    );
  }
  f = message.getRunCallableResponse();
  if (f != null) {
    writer.writeMessage(
      29,
      f,
      tensorflow_core_protobuf_master_pb.RunCallableResponse.serializeBinaryToWriter
    );
  }
  f = message.getReleaseCallableResponse();
  if (f != null) {
    writer.writeMessage(
      30,
      f,
      tensorflow_core_protobuf_master_pb.ReleaseCallableResponse.serializeBinaryToWriter
    );
  }
};


/**
 * optional double start_time_us = 31;
 * @return {number}
 */
proto.tensorflow.ReplayOp.prototype.getStartTimeUs = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 31, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.tensorflow.ReplayOp} returns this
 */
proto.tensorflow.ReplayOp.prototype.setStartTimeUs = function(value) {
  return jspb.Message.setProto3FloatField(this, 31, value);
};


/**
 * optional double end_time_us = 32;
 * @return {number}
 */
proto.tensorflow.ReplayOp.prototype.getEndTimeUs = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 32, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.tensorflow.ReplayOp} returns this
 */
proto.tensorflow.ReplayOp.prototype.setEndTimeUs = function(value) {
  return jspb.Message.setProto3FloatField(this, 32, value);
};


/**
 * optional CreateSessionRequest create_session = 1;
 * @return {?proto.tensorflow.CreateSessionRequest}
 */
proto.tensorflow.ReplayOp.prototype.getCreateSession = function() {
  return /** @type{?proto.tensorflow.CreateSessionRequest} */ (
    jspb.Message.getWrapperField(this, tensorflow_core_protobuf_master_pb.CreateSessionRequest, 1));
};


/**
 * @param {?proto.tensorflow.CreateSessionRequest|undefined} value
 * @return {!proto.tensorflow.ReplayOp} returns this
*/
proto.tensorflow.ReplayOp.prototype.setCreateSession = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.tensorflow.ReplayOp.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.tensorflow.ReplayOp} returns this
 */
proto.tensorflow.ReplayOp.prototype.clearCreateSession = function() {
  return this.setCreateSession(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tensorflow.ReplayOp.prototype.hasCreateSession = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional ExtendSessionRequest extend_session = 2;
 * @return {?proto.tensorflow.ExtendSessionRequest}
 */
proto.tensorflow.ReplayOp.prototype.getExtendSession = function() {
  return /** @type{?proto.tensorflow.ExtendSessionRequest} */ (
    jspb.Message.getWrapperField(this, tensorflow_core_protobuf_master_pb.ExtendSessionRequest, 2));
};


/**
 * @param {?proto.tensorflow.ExtendSessionRequest|undefined} value
 * @return {!proto.tensorflow.ReplayOp} returns this
*/
proto.tensorflow.ReplayOp.prototype.setExtendSession = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.tensorflow.ReplayOp.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.tensorflow.ReplayOp} returns this
 */
proto.tensorflow.ReplayOp.prototype.clearExtendSession = function() {
  return this.setExtendSession(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tensorflow.ReplayOp.prototype.hasExtendSession = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional PartialRunSetupRequest partial_run_setup = 3;
 * @return {?proto.tensorflow.PartialRunSetupRequest}
 */
proto.tensorflow.ReplayOp.prototype.getPartialRunSetup = function() {
  return /** @type{?proto.tensorflow.PartialRunSetupRequest} */ (
    jspb.Message.getWrapperField(this, tensorflow_core_protobuf_master_pb.PartialRunSetupRequest, 3));
};


/**
 * @param {?proto.tensorflow.PartialRunSetupRequest|undefined} value
 * @return {!proto.tensorflow.ReplayOp} returns this
*/
proto.tensorflow.ReplayOp.prototype.setPartialRunSetup = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.tensorflow.ReplayOp.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.tensorflow.ReplayOp} returns this
 */
proto.tensorflow.ReplayOp.prototype.clearPartialRunSetup = function() {
  return this.setPartialRunSetup(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tensorflow.ReplayOp.prototype.hasPartialRunSetup = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional RunStepRequest run_step = 4;
 * @return {?proto.tensorflow.RunStepRequest}
 */
proto.tensorflow.ReplayOp.prototype.getRunStep = function() {
  return /** @type{?proto.tensorflow.RunStepRequest} */ (
    jspb.Message.getWrapperField(this, tensorflow_core_protobuf_master_pb.RunStepRequest, 4));
};


/**
 * @param {?proto.tensorflow.RunStepRequest|undefined} value
 * @return {!proto.tensorflow.ReplayOp} returns this
*/
proto.tensorflow.ReplayOp.prototype.setRunStep = function(value) {
  return jspb.Message.setOneofWrapperField(this, 4, proto.tensorflow.ReplayOp.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.tensorflow.ReplayOp} returns this
 */
proto.tensorflow.ReplayOp.prototype.clearRunStep = function() {
  return this.setRunStep(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tensorflow.ReplayOp.prototype.hasRunStep = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional CloseSessionRequest close_session = 5;
 * @return {?proto.tensorflow.CloseSessionRequest}
 */
proto.tensorflow.ReplayOp.prototype.getCloseSession = function() {
  return /** @type{?proto.tensorflow.CloseSessionRequest} */ (
    jspb.Message.getWrapperField(this, tensorflow_core_protobuf_master_pb.CloseSessionRequest, 5));
};


/**
 * @param {?proto.tensorflow.CloseSessionRequest|undefined} value
 * @return {!proto.tensorflow.ReplayOp} returns this
*/
proto.tensorflow.ReplayOp.prototype.setCloseSession = function(value) {
  return jspb.Message.setOneofWrapperField(this, 5, proto.tensorflow.ReplayOp.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.tensorflow.ReplayOp} returns this
 */
proto.tensorflow.ReplayOp.prototype.clearCloseSession = function() {
  return this.setCloseSession(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tensorflow.ReplayOp.prototype.hasCloseSession = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional ListDevicesRequest list_devices = 6;
 * @return {?proto.tensorflow.ListDevicesRequest}
 */
proto.tensorflow.ReplayOp.prototype.getListDevices = function() {
  return /** @type{?proto.tensorflow.ListDevicesRequest} */ (
    jspb.Message.getWrapperField(this, tensorflow_core_protobuf_master_pb.ListDevicesRequest, 6));
};


/**
 * @param {?proto.tensorflow.ListDevicesRequest|undefined} value
 * @return {!proto.tensorflow.ReplayOp} returns this
*/
proto.tensorflow.ReplayOp.prototype.setListDevices = function(value) {
  return jspb.Message.setOneofWrapperField(this, 6, proto.tensorflow.ReplayOp.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.tensorflow.ReplayOp} returns this
 */
proto.tensorflow.ReplayOp.prototype.clearListDevices = function() {
  return this.setListDevices(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tensorflow.ReplayOp.prototype.hasListDevices = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional ResetRequest reset_request = 7;
 * @return {?proto.tensorflow.ResetRequest}
 */
proto.tensorflow.ReplayOp.prototype.getResetRequest = function() {
  return /** @type{?proto.tensorflow.ResetRequest} */ (
    jspb.Message.getWrapperField(this, tensorflow_core_protobuf_master_pb.ResetRequest, 7));
};


/**
 * @param {?proto.tensorflow.ResetRequest|undefined} value
 * @return {!proto.tensorflow.ReplayOp} returns this
*/
proto.tensorflow.ReplayOp.prototype.setResetRequest = function(value) {
  return jspb.Message.setOneofWrapperField(this, 7, proto.tensorflow.ReplayOp.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.tensorflow.ReplayOp} returns this
 */
proto.tensorflow.ReplayOp.prototype.clearResetRequest = function() {
  return this.setResetRequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tensorflow.ReplayOp.prototype.hasResetRequest = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional MakeCallableRequest make_callable = 8;
 * @return {?proto.tensorflow.MakeCallableRequest}
 */
proto.tensorflow.ReplayOp.prototype.getMakeCallable = function() {
  return /** @type{?proto.tensorflow.MakeCallableRequest} */ (
    jspb.Message.getWrapperField(this, tensorflow_core_protobuf_master_pb.MakeCallableRequest, 8));
};


/**
 * @param {?proto.tensorflow.MakeCallableRequest|undefined} value
 * @return {!proto.tensorflow.ReplayOp} returns this
*/
proto.tensorflow.ReplayOp.prototype.setMakeCallable = function(value) {
  return jspb.Message.setOneofWrapperField(this, 8, proto.tensorflow.ReplayOp.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.tensorflow.ReplayOp} returns this
 */
proto.tensorflow.ReplayOp.prototype.clearMakeCallable = function() {
  return this.setMakeCallable(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tensorflow.ReplayOp.prototype.hasMakeCallable = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional RunCallableRequest run_callable = 9;
 * @return {?proto.tensorflow.RunCallableRequest}
 */
proto.tensorflow.ReplayOp.prototype.getRunCallable = function() {
  return /** @type{?proto.tensorflow.RunCallableRequest} */ (
    jspb.Message.getWrapperField(this, tensorflow_core_protobuf_master_pb.RunCallableRequest, 9));
};


/**
 * @param {?proto.tensorflow.RunCallableRequest|undefined} value
 * @return {!proto.tensorflow.ReplayOp} returns this
*/
proto.tensorflow.ReplayOp.prototype.setRunCallable = function(value) {
  return jspb.Message.setOneofWrapperField(this, 9, proto.tensorflow.ReplayOp.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.tensorflow.ReplayOp} returns this
 */
proto.tensorflow.ReplayOp.prototype.clearRunCallable = function() {
  return this.setRunCallable(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tensorflow.ReplayOp.prototype.hasRunCallable = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional ReleaseCallableRequest release_callable = 10;
 * @return {?proto.tensorflow.ReleaseCallableRequest}
 */
proto.tensorflow.ReplayOp.prototype.getReleaseCallable = function() {
  return /** @type{?proto.tensorflow.ReleaseCallableRequest} */ (
    jspb.Message.getWrapperField(this, tensorflow_core_protobuf_master_pb.ReleaseCallableRequest, 10));
};


/**
 * @param {?proto.tensorflow.ReleaseCallableRequest|undefined} value
 * @return {!proto.tensorflow.ReplayOp} returns this
*/
proto.tensorflow.ReplayOp.prototype.setReleaseCallable = function(value) {
  return jspb.Message.setOneofWrapperField(this, 10, proto.tensorflow.ReplayOp.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.tensorflow.ReplayOp} returns this
 */
proto.tensorflow.ReplayOp.prototype.clearReleaseCallable = function() {
  return this.setReleaseCallable(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tensorflow.ReplayOp.prototype.hasReleaseCallable = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional NewReplaySession new_replay_session = 11;
 * @return {?proto.tensorflow.NewReplaySession}
 */
proto.tensorflow.ReplayOp.prototype.getNewReplaySession = function() {
  return /** @type{?proto.tensorflow.NewReplaySession} */ (
    jspb.Message.getWrapperField(this, proto.tensorflow.NewReplaySession, 11));
};


/**
 * @param {?proto.tensorflow.NewReplaySession|undefined} value
 * @return {!proto.tensorflow.ReplayOp} returns this
*/
proto.tensorflow.ReplayOp.prototype.setNewReplaySession = function(value) {
  return jspb.Message.setOneofWrapperField(this, 11, proto.tensorflow.ReplayOp.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.tensorflow.ReplayOp} returns this
 */
proto.tensorflow.ReplayOp.prototype.clearNewReplaySession = function() {
  return this.setNewReplaySession(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tensorflow.ReplayOp.prototype.hasNewReplaySession = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional CreateSessionResponse create_session_response = 21;
 * @return {?proto.tensorflow.CreateSessionResponse}
 */
proto.tensorflow.ReplayOp.prototype.getCreateSessionResponse = function() {
  return /** @type{?proto.tensorflow.CreateSessionResponse} */ (
    jspb.Message.getWrapperField(this, tensorflow_core_protobuf_master_pb.CreateSessionResponse, 21));
};


/**
 * @param {?proto.tensorflow.CreateSessionResponse|undefined} value
 * @return {!proto.tensorflow.ReplayOp} returns this
*/
proto.tensorflow.ReplayOp.prototype.setCreateSessionResponse = function(value) {
  return jspb.Message.setOneofWrapperField(this, 21, proto.tensorflow.ReplayOp.oneofGroups_[1], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.tensorflow.ReplayOp} returns this
 */
proto.tensorflow.ReplayOp.prototype.clearCreateSessionResponse = function() {
  return this.setCreateSessionResponse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tensorflow.ReplayOp.prototype.hasCreateSessionResponse = function() {
  return jspb.Message.getField(this, 21) != null;
};


/**
 * optional ExtendSessionResponse extend_session_response = 22;
 * @return {?proto.tensorflow.ExtendSessionResponse}
 */
proto.tensorflow.ReplayOp.prototype.getExtendSessionResponse = function() {
  return /** @type{?proto.tensorflow.ExtendSessionResponse} */ (
    jspb.Message.getWrapperField(this, tensorflow_core_protobuf_master_pb.ExtendSessionResponse, 22));
};


/**
 * @param {?proto.tensorflow.ExtendSessionResponse|undefined} value
 * @return {!proto.tensorflow.ReplayOp} returns this
*/
proto.tensorflow.ReplayOp.prototype.setExtendSessionResponse = function(value) {
  return jspb.Message.setOneofWrapperField(this, 22, proto.tensorflow.ReplayOp.oneofGroups_[1], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.tensorflow.ReplayOp} returns this
 */
proto.tensorflow.ReplayOp.prototype.clearExtendSessionResponse = function() {
  return this.setExtendSessionResponse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tensorflow.ReplayOp.prototype.hasExtendSessionResponse = function() {
  return jspb.Message.getField(this, 22) != null;
};


/**
 * optional PartialRunSetupResponse partial_run_setup_response = 23;
 * @return {?proto.tensorflow.PartialRunSetupResponse}
 */
proto.tensorflow.ReplayOp.prototype.getPartialRunSetupResponse = function() {
  return /** @type{?proto.tensorflow.PartialRunSetupResponse} */ (
    jspb.Message.getWrapperField(this, tensorflow_core_protobuf_master_pb.PartialRunSetupResponse, 23));
};


/**
 * @param {?proto.tensorflow.PartialRunSetupResponse|undefined} value
 * @return {!proto.tensorflow.ReplayOp} returns this
*/
proto.tensorflow.ReplayOp.prototype.setPartialRunSetupResponse = function(value) {
  return jspb.Message.setOneofWrapperField(this, 23, proto.tensorflow.ReplayOp.oneofGroups_[1], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.tensorflow.ReplayOp} returns this
 */
proto.tensorflow.ReplayOp.prototype.clearPartialRunSetupResponse = function() {
  return this.setPartialRunSetupResponse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tensorflow.ReplayOp.prototype.hasPartialRunSetupResponse = function() {
  return jspb.Message.getField(this, 23) != null;
};


/**
 * optional RunStepResponse run_step_response = 24;
 * @return {?proto.tensorflow.RunStepResponse}
 */
proto.tensorflow.ReplayOp.prototype.getRunStepResponse = function() {
  return /** @type{?proto.tensorflow.RunStepResponse} */ (
    jspb.Message.getWrapperField(this, tensorflow_core_protobuf_master_pb.RunStepResponse, 24));
};


/**
 * @param {?proto.tensorflow.RunStepResponse|undefined} value
 * @return {!proto.tensorflow.ReplayOp} returns this
*/
proto.tensorflow.ReplayOp.prototype.setRunStepResponse = function(value) {
  return jspb.Message.setOneofWrapperField(this, 24, proto.tensorflow.ReplayOp.oneofGroups_[1], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.tensorflow.ReplayOp} returns this
 */
proto.tensorflow.ReplayOp.prototype.clearRunStepResponse = function() {
  return this.setRunStepResponse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tensorflow.ReplayOp.prototype.hasRunStepResponse = function() {
  return jspb.Message.getField(this, 24) != null;
};


/**
 * optional CloseSessionResponse close_session_response = 25;
 * @return {?proto.tensorflow.CloseSessionResponse}
 */
proto.tensorflow.ReplayOp.prototype.getCloseSessionResponse = function() {
  return /** @type{?proto.tensorflow.CloseSessionResponse} */ (
    jspb.Message.getWrapperField(this, tensorflow_core_protobuf_master_pb.CloseSessionResponse, 25));
};


/**
 * @param {?proto.tensorflow.CloseSessionResponse|undefined} value
 * @return {!proto.tensorflow.ReplayOp} returns this
*/
proto.tensorflow.ReplayOp.prototype.setCloseSessionResponse = function(value) {
  return jspb.Message.setOneofWrapperField(this, 25, proto.tensorflow.ReplayOp.oneofGroups_[1], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.tensorflow.ReplayOp} returns this
 */
proto.tensorflow.ReplayOp.prototype.clearCloseSessionResponse = function() {
  return this.setCloseSessionResponse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tensorflow.ReplayOp.prototype.hasCloseSessionResponse = function() {
  return jspb.Message.getField(this, 25) != null;
};


/**
 * optional ListDevicesResponse list_devices_response = 26;
 * @return {?proto.tensorflow.ListDevicesResponse}
 */
proto.tensorflow.ReplayOp.prototype.getListDevicesResponse = function() {
  return /** @type{?proto.tensorflow.ListDevicesResponse} */ (
    jspb.Message.getWrapperField(this, tensorflow_core_protobuf_master_pb.ListDevicesResponse, 26));
};


/**
 * @param {?proto.tensorflow.ListDevicesResponse|undefined} value
 * @return {!proto.tensorflow.ReplayOp} returns this
*/
proto.tensorflow.ReplayOp.prototype.setListDevicesResponse = function(value) {
  return jspb.Message.setOneofWrapperField(this, 26, proto.tensorflow.ReplayOp.oneofGroups_[1], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.tensorflow.ReplayOp} returns this
 */
proto.tensorflow.ReplayOp.prototype.clearListDevicesResponse = function() {
  return this.setListDevicesResponse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tensorflow.ReplayOp.prototype.hasListDevicesResponse = function() {
  return jspb.Message.getField(this, 26) != null;
};


/**
 * optional ResetResponse reset_request_response = 27;
 * @return {?proto.tensorflow.ResetResponse}
 */
proto.tensorflow.ReplayOp.prototype.getResetRequestResponse = function() {
  return /** @type{?proto.tensorflow.ResetResponse} */ (
    jspb.Message.getWrapperField(this, tensorflow_core_protobuf_master_pb.ResetResponse, 27));
};


/**
 * @param {?proto.tensorflow.ResetResponse|undefined} value
 * @return {!proto.tensorflow.ReplayOp} returns this
*/
proto.tensorflow.ReplayOp.prototype.setResetRequestResponse = function(value) {
  return jspb.Message.setOneofWrapperField(this, 27, proto.tensorflow.ReplayOp.oneofGroups_[1], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.tensorflow.ReplayOp} returns this
 */
proto.tensorflow.ReplayOp.prototype.clearResetRequestResponse = function() {
  return this.setResetRequestResponse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tensorflow.ReplayOp.prototype.hasResetRequestResponse = function() {
  return jspb.Message.getField(this, 27) != null;
};


/**
 * optional MakeCallableResponse make_callable_response = 28;
 * @return {?proto.tensorflow.MakeCallableResponse}
 */
proto.tensorflow.ReplayOp.prototype.getMakeCallableResponse = function() {
  return /** @type{?proto.tensorflow.MakeCallableResponse} */ (
    jspb.Message.getWrapperField(this, tensorflow_core_protobuf_master_pb.MakeCallableResponse, 28));
};


/**
 * @param {?proto.tensorflow.MakeCallableResponse|undefined} value
 * @return {!proto.tensorflow.ReplayOp} returns this
*/
proto.tensorflow.ReplayOp.prototype.setMakeCallableResponse = function(value) {
  return jspb.Message.setOneofWrapperField(this, 28, proto.tensorflow.ReplayOp.oneofGroups_[1], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.tensorflow.ReplayOp} returns this
 */
proto.tensorflow.ReplayOp.prototype.clearMakeCallableResponse = function() {
  return this.setMakeCallableResponse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tensorflow.ReplayOp.prototype.hasMakeCallableResponse = function() {
  return jspb.Message.getField(this, 28) != null;
};


/**
 * optional RunCallableResponse run_callable_response = 29;
 * @return {?proto.tensorflow.RunCallableResponse}
 */
proto.tensorflow.ReplayOp.prototype.getRunCallableResponse = function() {
  return /** @type{?proto.tensorflow.RunCallableResponse} */ (
    jspb.Message.getWrapperField(this, tensorflow_core_protobuf_master_pb.RunCallableResponse, 29));
};


/**
 * @param {?proto.tensorflow.RunCallableResponse|undefined} value
 * @return {!proto.tensorflow.ReplayOp} returns this
*/
proto.tensorflow.ReplayOp.prototype.setRunCallableResponse = function(value) {
  return jspb.Message.setOneofWrapperField(this, 29, proto.tensorflow.ReplayOp.oneofGroups_[1], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.tensorflow.ReplayOp} returns this
 */
proto.tensorflow.ReplayOp.prototype.clearRunCallableResponse = function() {
  return this.setRunCallableResponse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tensorflow.ReplayOp.prototype.hasRunCallableResponse = function() {
  return jspb.Message.getField(this, 29) != null;
};


/**
 * optional ReleaseCallableResponse release_callable_response = 30;
 * @return {?proto.tensorflow.ReleaseCallableResponse}
 */
proto.tensorflow.ReplayOp.prototype.getReleaseCallableResponse = function() {
  return /** @type{?proto.tensorflow.ReleaseCallableResponse} */ (
    jspb.Message.getWrapperField(this, tensorflow_core_protobuf_master_pb.ReleaseCallableResponse, 30));
};


/**
 * @param {?proto.tensorflow.ReleaseCallableResponse|undefined} value
 * @return {!proto.tensorflow.ReplayOp} returns this
*/
proto.tensorflow.ReplayOp.prototype.setReleaseCallableResponse = function(value) {
  return jspb.Message.setOneofWrapperField(this, 30, proto.tensorflow.ReplayOp.oneofGroups_[1], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.tensorflow.ReplayOp} returns this
 */
proto.tensorflow.ReplayOp.prototype.clearReleaseCallableResponse = function() {
  return this.setReleaseCallableResponse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tensorflow.ReplayOp.prototype.hasReleaseCallableResponse = function() {
  return jspb.Message.getField(this, 30) != null;
};


goog.object.extend(exports, proto.tensorflow);
